name: "acceptance tests"
on:
  push:
    branches: "*"
jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: 'v1.13.1'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: run acceptance tests
        run: |
          KUBE_CTX_CLUSTER=minikube KUBECONFIG=~/.kube/config \
            make testacc
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: run unit tests
        run: |
          make test
